# Utiliser une image de base minimale
FROM python:3.10-slim AS base

# COPY requirements.txt ../requirements.txt

# Définir le répertoire de travail
WORKDIR /src

# Copier uniquement le fichier de dépendances pour profiter du cache
COPY requirements.txt .


# Installer les dépendances et nettoyer le cache pip pour réduire la taille
RUN pip install --upgrade pip setuptools wheel && \
    pip install --no-cache-dir -r requirements.txt


# Copier le code source
COPY . .

# Vérifier que les fichiers sont bien copiés
RUN ls -la /src

# Déclarer la variable d'environnement pour Flask
ENV FLASK_APP=src/app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_DEBUG=1


# Exposer le port utilisé par l'application Flask
EXPOSE 5000

# Commande pour démarrer l'application
CMD ["flask", "run"]
